## 无法恢复的错误

某种行为造成程序崩溃或者主动调用 panic! 宏。默认情况下，这些 panic 将打印失败消息、清理堆栈并退出。通过环境变量，还可以让 Rust 在发生 panic 时显示调用的堆栈，以便更容易追踪 panic 的来源。

尝试调用 panic!：

```rust
fn main() {
    panic!("crash and burn");
}
```

运行后的输出：

```shell
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/panic`
thread 'main' panicked at 'crash and burn', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

尝试访问超出有效范围的数组索引：

```rust
fn main() {
    let v = vec![1, 2, 3];

    v[99];
}
```

运行后的输出：

```shell
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/panic`
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## 可恢复的错误

例如，如果您尝试打开一个文件，但该操作因文件不存在而失败，您可能希望创建该文件而不是终止进程。

回顾一下 Result 枚举：

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

T 和 E 都是范型，分别是变体 Ok 和 Err 持有的数据类型。

一个返回 Result 的例子：

```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
```

File::open 返回 Result<T, E>。T 的类型是 std::fs::File，E 的类型是 std::io::Error。

文件可能不存在也可能没有权限。如果不存在，我们希望新建一个文件并返回该文件的句柄，如不没有权限则调用 panic!。

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error);
            }
        },
    };
}
```

### unwrap 和 expect

使用 match 效果很好，但它可能有点冗长并且并不总是能很好地传达意图。Result 的 unwrap 方法有点像 match 表达式。如果 Result 值是 Ok 变体，unwrap 将返回 Ok 内部的值。如果 Result 是 Err 变体，unwrap 将调用 panic! 宏。expect 与 unwrap 相似，不过可以指定 panic! 的错误消息。

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap();
}
```

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")
        .expect("hello.txt should be included in this project");
}
```

### 传播错误

当一个函数的实现调用可能失败的东西时，您可以将错误返回给调用代码，而不是在函数本身内处理错误。

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
```

我们先看函数的返回类型是 Result<T, E>。其中泛型参数 T 已填充为具体类型 String，而泛型类型 E 已填充为具体类型 io::Error。Rust 提供问号运算符 ? 使这更容易。

用 ? 符号缩写以上代码：

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

这 ？放置在 Result 值之后，其工作方式几乎与我们定义的用于处理 Result 值的 match 表达式相同。如果值为 Err，则 Err 将从整个函数返回，就好像我们使用了 return 关键字一样，因此错误值会传播到调用代码。

通过链式方法缩写：

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;

    Ok(username)
}
```

标准库函数提供了方便的方法，所以可以进一步缩写：

```rust
use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

? 也可以与 `Option<T>` 一起使用，例如：

```rust
fn last_char_of_first_line(text: &str) -> Option<char> {
    text.lines().next()?.chars().last()
}
```

在迭代器上调用 next 以从迭代器中获取第一个值。如果 text 是空字符串，对 next 的调用将返回 None，在这种情况下我们使用 ? 从 last_char_of_first_line 停止并返回 None。
